# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LazyJson < Formula
  desc "Keyboard-first JSON viewer and editor for the terminal"
  homepage "https://github.com/anyroad/lazy-json"
  version "0.9.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anyroad/lazy-json/releases/download/v0.9.4/lazy-json_0.9.4_darwin_amd64.tar.gz"
      sha256 "8c454b569899a65c7a02ce021da29f0c5a52786cd21e4e8bff2f0c79655a1b9c"

      define_method(:install) do
        bin.install "lazy-json"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anyroad/lazy-json/releases/download/v0.9.4/lazy-json_0.9.4_darwin_arm64.tar.gz"
      sha256 "110d9dfa3c6ea120824a3fe82c87dde3c913407f43d58f3084d2075e1221c1bf"

      define_method(:install) do
        bin.install "lazy-json"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anyroad/lazy-json/releases/download/v0.9.4/lazy-json_0.9.4_linux_amd64.tar.gz"
      sha256 "fe6f87165fceb175de7ddfe7786c73e6cf4c093592afcaf4e89f023a37d7aa09"
      define_method(:install) do
        bin.install "lazy-json"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anyroad/lazy-json/releases/download/v0.9.4/lazy-json_0.9.4_linux_arm64.tar.gz"
      sha256 "114eb3c2cb156d5d284d97a4c798000e7df6c301d559acefb68ca565dfe54473"
      define_method(:install) do
        bin.install "lazy-json"
      end
    end
  end

  test do
    system "#{bin}/lazy-json", "--version"
  end
end
